### ISSUE TITLE
add ability to query pubkeys (`mempool.space/pubkey/<pubkey>`) + other ideas

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1075]
### Description

add ability to query pubkeys just like you can query addresses https://mempool.space/testnet/address/tb1qsgx55dp6gn53tsmyjjv4c2ye403hgxynxs0dnm

pubkey query would look something like https://mempool.space/pubkey/04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f

### Problem to be solved

being unable to browse transactions by pubkey (P2PK was used in the early bitcoin days)

example p2pk [tx](https://mempool.space/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16)
![image](https://user-images.githubusercontent.com/49868160/147832045-a0747561-8594-481e-b280-f3a84fb1da50.png)

### Proposed solution

- mempool.space/pubkey/<pubkey>
- `P2PK` in screenshot above get replaced with a link just like p2wpkh and other addresses 

#### Additional info

you can query electrs by scriptPubKey, right? then this should be possible

**Comment by antonilol** [comment]
or even better, by locking script / scriptPubKey

**Comment by antonilol** [comment]
![image](https://user-images.githubusercontent.com/49868160/148260204-43009252-79f1-42d5-8892-27299504db1b.png)

this would also be cool (public keys are disclosed when someone spends at least once from an address)

![image](https://user-images.githubusercontent.com/49868160/148260513-74b543ef-eadd-4bfc-9650-eb7f5269b7fa.png)
^ this would not be possible but just for the screenshot (amount sent != 0 and public key not revealed)

**Comment by antonilol** [comment]
edited https://github.com/mempool/mempool/issues/1075#issuecomment-1003701950

**Comment by antonilol** [comment]
and....
![image](https://user-images.githubusercontent.com/49868160/148537493-a56542d4-8506-494c-b0a3-8564759b9c81.png)
such a menu on a p2wsh-multisig address would be cool with under the public key clickable link to that public key. that public key page would also have a list of places where that public key is used.
(keep in mind that just like https://github.com/mempool/mempool/issues/1075#issuecomment-1005920652 public keys in a script get revealed when something gets spent from that address)

**Comment by junderw** [comment]
I will close this as a "will not implement"

1. One utxo to the DER uncompressed P2PK, one utxo to the DER compressed P2PK, to we group them? They are the same pubkey just different representations. The scriptPubkeys are different. Offering a pubkey query endpoint opens a can of worms to "why can't you show also any P2SH/P2SH-P2WSH/P2WSH/raw multisig that have revealed to include my pubkey as one of my UTXOs as well? etc... it seems like a support nightmare.
2. Re: Showing pubkeys. This is only really useful if we have a pubkey query API, otherwise this info is not helpful besides being cool to look at. Not to mention the implications on this from taproot are a huge can of worms we shouldn't really get into imo (the whole point of taproot being "this pubkey MIGHT be a single pubkey OR it might not... you may never know!")
