### ISSUE TITLE
"UNKNOWN" is missing from addresses when using romanz/electrs backend

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#1262]
https://mempool.nixbitcoin.org/tx/2579d418e2ac6af674d45bbe02b87193329581a1a1a55ef162a9a47b6d18d0ac

vs

https://mempool.space/tx/2579d418e2ac6af674d45bbe02b87193329581a1a1a55ef162a9a47b6d18d0ac

**Comment by antonilol** [comment]
for some `OP_RETURN` outputs local hosted mempool calls the script type `NONSTANDARD`




#1260

**Comment by softsimon** [comment]
I can't figure out the cause of this because I get different result on different systems here in Bitcoin Core mode. Different Bitcoin Core version?

This is what I get on Raspiblitz with Bitcoin Core v22

<img width="584" alt="Screen Shot 2022-02-20 at 22 09 36" src="https://user-images.githubusercontent.com/8561090/154857325-8ea9d36f-f84c-40bf-ae9e-71ef860228f3.png">

**Comment by antonilol** [comment]
it is very likely you have `deprecatedrpc=addresses` in your bitcoin.conf. bitcoin core will give addresses of public keys used in a multisig script with the `decodescript` rpc.
`deprecatedrpc=addresses` was needed with core v22 + mempool v2.2
