### ISSUE TITLE
Add Javascript Prerender to support noscript environment

### ISSUE THREAD

**Issue by 0xAyanami** [mempool/mempool#1386]
### Description

It would be great to add Javascript Prerender for Mempool so there would be no javascript required on user's side.

Example)

Blockstream.info, which is an another explorer supporting onion address, supports noscript by rendering javascript from server-side using prerender service 

https://github.com/Blockstream/esplora/tree/master/prerender-server

https://github.com/Blockstream/esplora/commit/a21b4a040687ed1412630db9597a945dab2a91e0

More info about rendering javascript server-side by Airbnb

https://medium.com/airbnb-engineering/operationalizing-node-js-for-server-side-rendering-c5ba718acfc9

### Problem to be solved

Support noscript environment for mempool to endorse users block javascript when surfing on Tor.

### Proposed solution

Add prerender service

#### Additional info

https://github.com/Blockstream/esplora/tree/master/prerender-server

https://github.com/Blockstream/esplora/commit/a21b4a040687ed1412630db9597a945dab2a91e0

https://medium.com/airbnb-engineering/operationalizing-node-js-for-server-side-rendering-c5ba718acfc9

**Comment by wiz** [comment]
Yes, we added server side rendering using Angular Universal a few years back but never shipped it due to some issues we need to work out. It's on the task list but not a high priority item right now.

**Comment by 0xAyanami** [comment]
@wiz Looks like it would need a lot of refactoring with frontend codes but once they are done, we will be able to ship one of the safest, privacy focused open source bitcoin block explorer again.

Or, how about creating some kind of bounty / funding to complete this milestone? Since many people using Tor Browser would completely disable javascript to preserve privacy for any kind of onion sites, it would mean a lot to the bitcoin community.

**Comment by wiz** [comment]
If you're concerned about privacy then you should simply run your own self-hosted mempool instance on inexpensive hardware at home. We've worked very hard to support one-click installations on all the popular Raspberry Pi fullnode distros, and this is best for all our users since even if you disable JS execution and use Tor browser, you're still sending all your TXIDs and addresses to our backend, and you're trusting those results and trusting us not to log you.

While we've looked into it and worked on it in the past, the conclusion from our side is basically that developing, shipping, and maintaining a no-js version of mempool.space is a lot of work for a very small benefit for a very small group of users, so it's a low priority task for us. Our development and operations resources are very limited so we need to prioritize more important major new functionality.
