### ISSUE TITLE
Improve responsiveness on the miner details page

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#1406]
The addresses and tags lists are scrolling on mobile

![45D14DB8-2A58-4A72-BE25-1AAF1DF78CFF](https://user-images.githubusercontent.com/100320/159022773-1558ae31-08d2-41b7-a483-c4683b0f8087.png)

**Comment by nymkappa** [comment]
Scolling is by design (_though it's not aligned well with other fields so I need to fix that_). It also scrolls on desktop when the list is long.

Do you have a suggestion on how to display those? For example, check `AntPool`, they have lot of addresses.
![image](https://user-images.githubusercontent.com/9780671/159217607-81d6fd9e-1f84-4316-83c8-4fbad1adf66e.png)

This also applies to regexes. Maybe a dropdown could be used instead?

**Comment by nymkappa** [comment]
@knorrium I cannot reproduce the vertical align issue on iphone/safari, did you take the screenshot while pull the addresses to the right or is that the default view after loading the page?

**Comment by nymkappa** [comment]
> Add scroll space, button/modal, or collapsible to the Addresses section. (if you check https://mempool.ninja/mining/pool/41, you can see that there are a few dozen addresses that need to be scrolled through, not sure if it is designed to be like that but it may be beneficial to see all the addresses at once via a button/modal or collapsible.
