### ISSUE TITLE
Address trimming should be dynamic based on windows size.

### ISSUE THREAD

**Issue by Transisto** [mempool/mempool#1465]
No matter how much free space there is, about 7 character will be replaced by 3 dots "..." making it hard to CTRL-F an address.

![image](https://user-images.githubusercontent.com/388716/160448513-3df1de95-6a43-4030-b7e0-6658920181d8.png)

**Comment by nymkappa** [comment]
I believe you are requesting two different improvements here:
* Improve truncation behavior so we don't have unnecessary blank spaces
* Provide a way to quickly highlight an address in a transaction. I know we have something for `txid` using url parameters, for example check out https://mempool.space/tx/a30a92627045a077029d0ca4c087062310618ba0b76782fabe4335915d0adaf1:1, maybe we can implement something similar for addresses. Maybe @softsimon has more insight on this.

PRs are welcome.

In the mean time, if you need to repeat this "CTRL F" operation often, try to use the API directly. For example using https://mempool.space/api/tx/a30a92627045a077029d0ca4c087062310618ba0b76782fabe4335915d0adaf1 you can "CTRL F" without any issue. If you use Firefox, the JSON will be automatically formatted, otherwise I recommend using a JSON parser extension.

**Comment by Transisto** [comment]
I just mean that full addresses should be displayed when there's room for
it.

Some people might want to just select and copy it?

**Comment by softsimon** [comment]
I have one suggestion that will solve this in most cases.

Add a monospace font just to display addresses on the page. We then don't have to shorten them to remove risk of overflow.

**Comment by nymkappa** [comment]
> I have one suggestion that will solve this in most cases.
> 
> Add a monospace font just to display addresses on the page. We then don't have to shorten them to remove risk of overflow. Segwit multisig addresses will still be too long but most won't.

Taproot addresses are 62 char long. Even with a monospace font it won't fit.

<img width="1213" alt="Screen Shot 2022-05-16 at 12 01 50 PM" src="https://user-images.githubusercontent.com/9780671/168568958-1f25f771-1a23-416c-8e10-72575ac7fb10.png">
