### ISSUE TITLE
API Timeout Issue on Local Node

### ISSUE THREAD

**Issue by BTCfan86** [mempool/mempool#1612]
Hello,

I am running the mempool app on a local node using Umbrel on a Raspberry Pi4.  When I try to query BTC address data through the mempool app in my browser, I get the following error:

Error loading address data.
(<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>       )

 A similar error occurs when trying to pull BTC address data from the mempool app on my local node using a script in python.  Is there a way to extend the time-out duration for the mempool app running on Umbrel?  I asked about a similar issue in a thread before (https://github.com/mempool/mempool/issues/1204),  but I wanted to ask again, including the error message above.

If the Raspberry Pi4 can't handle API calls like this, what kind of hardware do you think I would need to run mempool's production setup?  The suggested hardware seems pretty high-cost (20C CPU, 64G RAM)... Since I'm doing this for my own purposes and not as a business or corporate venture, I'm hoping to complete these kinds of API calls without spending quite so much money. Is there any middle ground hardware between my Pi4 and the 20C CPU production server that could accomplish these API pulls? Maybe running Umbrel / mempool app on a more powerful home PC instead of the Pi4 would be enough?  Thanks for your guidance on this.

**Comment by wiz** [comment]
This is a FAQ, but yes, address lookups are quite heavy, and the romanz/electrs backend together with low powered Raspberry Pi hardware means you can easily overload the backend, causing queries to timeout. It's outside the scope of the mempool open source project to provide an address index backend, but since we support the electrum server protocol you might try fulcrum backend as a middle between romanz/electrs and blockstream/electrs, I've heard it's about 1000x as efficient.
