### ISSUE TITLE
show cpfp information of confirmed txs

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1722]
### Description

title, when a confirmed transaction is spent or spends a transaction in the same block and the newer transaction has a higher fee rate, a cpfp was done. effective fee rate can be calculated from this

### Problem to be solved

more insight in fees, knowing why a 1 sat/vB tx is in a block with really high fees

### Proposed solution

add a cpfp button just like cpfp'd transactions in the mempool have (note that this button stays there after confirmation and is gone when you refresh the page)

#### Additional info

example:
https://mempool.space/tx/03de81f175033f6cb9d961fc03ad83c9b9f5ca82cfa5e5b2d35f85d2141a62c2 (not my tx)
it got cpfp'd with the 3rd output, found by scrolling through a block and looking for a transaction with lower fees that the one after it

tx 1: 5000 sat / 271.5 vB = 18.4 sat/vB
tx 2: 8903 sat / 190 vB = 46.9 sat/vB
both: (5000 + 8903) sat / (271.5 + 190) vB = 30.1 sat/vB (effective fee rate)

**Comment by softsimon** [comment]
The problem is that the CPFP info is calculated on the in-memory mempool, but once confirmed in blocks, the cpfp-relationships are lost.

We would require to
* Run a CPFP calculation of all the transactions in a block
* Store that information separately in our database

**Comment by antonilol** [comment]
> the cpfp-relationships are lost.

not completely, if tx B spends tx A and has a higher fee rate than A, then they will end up in the same block (and the link is thus preserved), but when tx A has a higher fee rate than B, there is no actual cpfp, the child doesnt pay for the parent, A will be confirmed first and when more of the mempool has been cleaned up (during mempool congestion) B will be confirmed. only in the 2nd case the link is lost because you cant tell from only the blockchain that both tx were in the mempool the same time

**Comment by junderw** [comment]
No need to restrict it to CPFP. Just show it as "Batched fee rate" or something. (Some unconfirmed chains are in descending spb order and would have been confirmed without any CPFP anyways, but just decided to lower their fee in response to mempool clearing etc.)

1. Parse block for all spend relations within the block
2. Group all spend relations and get a grouped spb calculation

If you want to restrict to CPFP, it becomes grey.

ie. if I have a chain of tx that goes 30 -> 25 -> 20 -> 21 -> 18 and the whole chain is confirmed in a block, did the 21 spb tx pay for the 3 generations of parents? As humans we can see that this is not reasonable...

So the heuristics of "What constitutes a CPFP" can be VERY grey.

"Batched fee rate" would be easy though.

**Comment by junderw** [comment]
"if the spb is greater than the average spb of all parents, uncles, grandparents etc. then it is CPFP unless the children and grandchildren are low enough spb to decrease the average of the tx and its descendants below the tx's parents and their ancestors."

Sounds like a sound explanation of a CPFP definition... but this is a pain to calculate when we can just display all batches.

**Comment by antonilol** [comment]
But a transaction with a lower batched/effective fee rate than its own fee rate doesnt make sense

> but this is a pain to calculate

Dont think so, but i can be overlooking something

**Comment by junderw** [comment]
That is literally what CPFP is: "My fee rate is set super high so that I can bring up my ancestor's average spb by including myself in the batch." so it will always be true that "My fee rate is higher than the batched fee rate IF I am attempting CPFP"

I think you meant to say the opposite: "But a transaction with a lower fee rate than its batched/effective fee rate doesnt make sense"

Everything doesn't have to make sense. People make wallet apps that have faulty logic. Fee estimations bug out randomly. etc. etc.

Working at an exchange, we put out txes at a set rate regardless of block frequency, and we use our own fee estimation.

Sometimes it bugs out and we send a tx @ 100 spb when the network only requires 10 spb... then we send another, and our algorithm finally catches up and sends the second tx @ 20 spb.

A = 100 spb
B (child of A) = 20 spb

This happens on the network all the time, BUT this is definitely NOT CPFP.

So finding a difference between "any old group of chained unconfirmed txes that were put in the same block" and "a group of unconfirmed txes that was a CPFP attempt" is confusing. 

Which is why I think it would be tons easier to just find every group of dependent txes that were confirmed in the same block and average their spb, then post their average spb on all of those tx info pages.

---

Example: I run an exchange that always pays 3x the current mempool "next block" estimate. For some reason a block isn't found for 1 hour, during that time my exchange has created a 25 tx deep unconfirmed chain. These are the individual spb for each tx and the "next block" spb estimate from mempool at the time of broadcast.

My estimator is horribly broken, so the actual mempool estimates from the mempool project.

Format: `(my tx spb) (my estimator spb) (mempool.space estimated spb)`

1. (30) (10) (3)
2. (30) (10) (3)
3. (30) (10) (3)
4. (30) (10) (3)
5. (30) (10) (3)
6. (30) (10) (3)
7. (30) (10) (3)

**Comment by junderw** [comment]
Any CPFP assuming logic is similar to the "change" assuming logic of blockchain . info (from a long time ago)

Yeah, most people assumed that if there were 2 outputs and one was a clean number, the other one must be change... but that is not always true.

This is why I would be against any feature to claim that something was CPFP.

However, I would be for a feature that shows the batched fee rate of multiple txes confirmed in the same block.

Whether or not that is CPFP is not useful.

If I made a CPFP and I want to see what rate I made it at after the fact, having the batched fee rate is enough... since I know which batch was mine and I know I was trying CPFP.
