### ISSUE TITLE
Mempool graph: Color for 350+ sats/vB transactions doesn't match the legend

### ISSUE THREAD

**Issue by jambolo** [mempool/mempool#283]
### Description

According to the legend, the color for 350+ sats/vByte transactions should be dark green, but the color in the graph is dark red.

#### Version

v2.0.0 (8b1768f7)

### Steps to reproduce

In the mempool graph, disable enough of the lower cost colors to see the 350+ sats/vByte transactions 

### Expected behaviour

The color of the the 350+ sats/vByte graph should be green

### Actual behaviour

The color of the 350+ sats/vByte graph is red

### Screenshots

![mempool-350+](https://user-images.githubusercontent.com/2095171/103424007-e1aaac80-4b5e-11eb-8381-344597bbe1eb.PNG)

**Comment by junderw** [comment]
This is caused because Chartist is only being given a-z as possibilities for the dynamic css class names. And there's 27 fee laters, so the last one wraps back around to `a` which makes it the same color as the first layer.

I tried adding `aa` after z, but it didn't fix it... Someone should check to see how Chartist works....... idk...

**Comment by junderw** [comment]
Note: #376 only fixes this issue by virtue of lowering the fee legend count from 27 to 26. The color issue will still persist for liquid

**Comment by jambolo** [comment]
Yes. The commit message has the wrong issue number. I believe that can be fixed when the PR is merged.
