### ISSUE TITLE
Mempool.space on RaspiBlitz displays wrong total received and total send

### ISSUE THREAD

**Issue by Emzy** [mempool/mempool#294]
### Description

Mempool.space on RaspiBlitz displayes most of the time the wrong numbers for the address "total received" and "total send".

#### Version

v2.0.1 (328511aa) 

### Steps to reproduce
Example address: 1Nm69gVnUmtLr8ghTrxMhVgNMvfDbSGv3j

### Screenshots

Wrong:
<img width="1142" alt="Screen Shot 2021-01-15 at 19 25 39" src="https://user-images.githubusercontent.com/1223908/104764287-76202c00-5767-11eb-809a-f25bd51b9775.png">
Right:
<img width="1141" alt="Screen Shot 2021-01-15 at 19 26 15" src="https://user-images.githubusercontent.com/1223908/104764338-8b955600-5767-11eb-9e87-564d13a5ffc3.png">

#### Device or machine

RaspiBlitz version v1.6.3-2021-01-13

**Comment by softsimon** [comment]
This is one issue was known but we skipped it to ship sooner https://github.com/mempool/mempool/pull/281

The problem is that electrum server doesn't return the received/sent amount on confirmed transactions. So we will decide on how to handle it... probably hide the fields completely when using romanz/electrs as address lookup backend.

Thanks @Emzy

**Comment by Emzy** [comment]
I agree, better not show it.
