### ISSUE TITLE
Block audit not handling multiple blocks arriving shortly after one another 

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#3650]
These two blocks arrived with just 3 (?) seconds in between each other.

This caused the second block to get a 0% health score. Perhaps we don't, and need to re-run the mempool template re-calculation after each block.

https://mempool.space/block/000000000000000000002f7ce47a66916b0abfe3dec8bd489d98ef161df1d3bc
https://mempool.space/block/00000000000000000001c20c14a52b5ae7c6ca385c58943c82ce8b0a76893b68

**Comment by TonyGiorgio** [comment]
@softsimon let me know if this should be a new issue, but it looks very similar to what I have just seen. 

These two blocks came in very close to each other, and the 2nd one seems pretty unhealthy to me. Probably just due to the quickness but instead of 100% it might need to at least add a disclaimer that there's insufficient time for miners to accurately process all the transactions? Not sure the best approach to take with it but I wouldn't call it 100% healthy unless this is the expectation under the circumstances in which case probably add a disclaimer?

![Screenshot from 2023-05-28 18-14-36](https://github.com/mempool/mempool/assets/101225832/d82c44a5-98dd-45f6-bda1-39be4e80a176)


https://mempool.space/block/00000000000000000000ef263c1a23ba30872e9982352562df5e84115b806050

The one before: https://mempool.space/block/000000000000000000002b175c4af34d56a4226b6cff992b00f3a171aa94e6e7

**Comment by mononaut** [comment]
This issue was fixed in PR #3655.

The poor results you noticed in block 791848 are ultimately caused by issue #3658 - the missing transactions in the expected block are all "high-sigop" transactions for which we currently overestimate mining priority.

In this case, the short block interval lowered the block's minimum rate below the apparent rates of a large number of such transactions, causing the extreme divergence in expected vs actual block templates.

The particular structure of that difference in templates does expose a flaw in our "marginal fee rate" audit heuristic, which produces the unexpectedly high health score and probably does warrant its own issue.
