### ISSUE TITLE
How can I check group addresses through api, for example, like https://blockchain.info/multiaddr?active=

### ISSUE THREAD

**Issue by developer-uz** [mempool/mempool#3730]

**Comment by Transisto** [comment]
I can't understand your example.
Do you have a functional link we could try?

**Comment by nymkappa** [comment]
We don't provide this API as of today and we don't have any plan to provide a public API for this purpose because querying addresses is resource intensive.

I recommend you to setup your own electrs instance and query it directly. You can use https://github.com/romanz/electrs for example, which can be installed in one click on Umbrel.
