### ISSUE TITLE
Expose first seen tx data via API

### ISSUE THREAD

**Issue by BullishNode** [mempool/mempool#3741]
### Description

Expose 'first seen' data in the API for an unconfirmed tx

### Problem to be solved

Wallet clients that are offline do not know at which time a transaction was received. It is useful for someone receiving payments to know that a customer paid at a certain time. It's an accounting, reporting, debugging, customer support feature. 

### Proposed solution

```
{
  txid: "15e10745f15593a899cef391191bdd3d7c12412cc4696b7bcb669d0feadc8521",
  version: 1,
  locktime: 0,
  vin: [],
  vout: [],
  size: 884,
  weight: 3536,
  fee: 20000,
  status: {
    confirmed: true,
    block_height: 363348,
    block_hash: "0000000000000000139385d7aa78ffb45469e0c715b8d6ea6cb2ffa98acc7171",
    block_time: 1683752831
    first_seen: 1683752528
  }
}
```

### Additional comment

I understand that someone operating a mempool server may not be "liable" for providing this kind of information. So perhaps it can be a configuration whether or not to provide access to this data via API. But it's still available on the front end, so why not provide it via API also? Would be really useful for me personally, for a BDK-based wallet I'm building.

**Comment by BullishNode** [comment]
An additional thought: this can help people align their expectations of confirmation times and plan better in the future. Identify whether they are overpaying or underpaying on average. Can yield some nice stats.

**Comment by BullishNode** [comment]
https://github.com/mempool/mempool/pull/2738

This PR has been stale for 7 months. Is this still planned?

**Comment by mononaut** [comment]
That PR was rejected due to excessive data requirements (storing the first-seen time for every transaction would add hundreds of thousands of rows to the MySQL database per day, which would degrade performance).

Hopefully we can reimplement it in some form using the new Redis KV store, but I don't think it's a top priority right now.

Meanwhile, first-seen times for unconfirmed transactions are available via `/api/v1/transaction-times?txId[]=...`, although this endpoint is currently undocumented and not guaranteed to remain stable.

First-seen times for confirmed transactions are not yet supported in any form (we simply don't store that data anywhere).

**Comment by BullishNode** [comment]
Ah okay I didn't know about that endpoint. Maybe that is good enough for what I want to do.
