### ISSUE TITLE
A block seems out of order.

### ISSUE THREAD

**Issue by nostitos** [mempool/mempool#4552]
![image](https://github.com/mempool/mempool/assets/48504624/c61acee3-278a-4a3d-9921-50b64d2f669b)

Since this morning I've been noticing blocks with lower fees than the rest in the middle of other blocks.

That one 

![image](https://github.com/mempool/mempool/assets/48504624/c57aa1f2-9f88-4255-be52-081e40930ab4)

**Comment by mononaut** [comment]
This is actually correct behavior, due to the presence of a very large number of "high-sigop" transactions which affects block construction.

Essentially each projected block can fit 80,000 sigops worth of the highest feerate transactions, followed by only (potentially lower rate) zero-sigop transactions up to the weight limit.

See also https://twitter.com/mononautical/status/1743274489893282187
