### ISSUE TITLE
Goggles coinjoin detection shows false positive

### ISSUE THREAD

**Issue by kristapsk** [mempool/mempool#4763]
### Description

Noticed this transaction marked as coinjoin - https://mempool.space/tx/46dd611e9846920b325e2b81a1e9c4e07882b2ba2853fd09f7eeaef10d154419. It certainly isn't, coinjoin transactions will never have such brutal address reuse in outputs. Also, 3GYcr6kCEkHuNc2VrngGddK7yskjEMT1pm is present on both input and output side.

#### Version

Current version running at https://mempool.space (at page bottom says "node202.fra.mempool.space (v3.0.0-dev) [[c55c298f](https://github.com/mempool/mempool/commit/c55c298f)][36d986c6]").

### Steps to reproduce

Toggled coinjoin goggle at current mempool.

### Expected behaviour

Transaction should not have been marked as coinjoin.

### Actual behaviour

Transaction was marked as coinjoin.

### Screenshots

![image](https://github.com/mempool/mempool/assets/4500994/b650dc7f-4d35-4a7e-9c98-d02501ed2d60)

**Comment by mononaut** [comment]
I'm not seeing that transaction marked as a coinjoin on node202.fra.mempool.space 🤔

And, in fact, the coinjoin detection rule has always disallowed address reuse on the output side of a transaction (although it permits some address reuse on the input side since #4647)

https://github.com/mempool/mempool/blob/93f547e4469bb2fdc40efce052becfffcbc109ae/backend/src/api/common.ts#L509-L512

I notice that `46dd611e...4419` is immediately next to a transaction that *is* correctly identified as a coinjoin in the block visualization - is it possible you clicked on the wrong transaction?

https://github.com/mempool/mempool/assets/83316221/9452a149-27f2-44e7-89f0-624f426be676

**Comment by kristapsk** [comment]
> I notice that `46dd611e...4419` is immediately next to a transaction that _is_ correctly identified as a coinjoin in the block visualization - is it possible you clicked on the wrong transaction?

It's most likely what happened. There was two coinjoins in mempool at that point and mined block now shows two coinjoins too, not this one and this tx is next to actual coinjoin, yes.

**Comment by kristapsk** [comment]
> tx.vin.length >= 5

Btw, in JoinMarket case this will filter out some coinjoins with less than 5 participiants, but they happen from time to time, `is_jm_tx()` in JoinMarket defaults to `min_participants = 3`. https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/7ebbacf1f450877b27db89d9a405bdd86e370086/src/jmbitcoin/secp256k1_transaction.py#L462

**Comment by mononaut** [comment]
thanks!
