### ISSUE TITLE
Disks at cursor line occlude part of chart under investigation

### ISSUE THREAD

**Issue by Xekyo** [mempool/mempool#829]
### Description

A key place of interest in a mempool chart are the times at which a block was found. E.g. this local peak in today's chart: 
![image](https://user-images.githubusercontent.com/4060799/134972098-5cc3fa3a-6411-43d2-8c98-ff75bff85d47.png)

While hovering over the chart, there are disks drawn over the intersections of the cursor line and the borders of feerate bands:
![image](https://user-images.githubusercontent.com/4060799/134972276-25ea2259-6745-46e3-b07d-3bd311cd1739.png)

Since the chart has sharp drops wherever blocks are found, and when hovering over such a time of interest to get the specific band depths, the mentioned disks occlude the most interesting part of the graph: 
![image](https://user-images.githubusercontent.com/4060799/134972470-78f216aa-c846-498a-9904-157cb0b55909.png)

Even when zooming in, the disks make it hard to see how much each band was affected by the newly issued block.
![image](https://user-images.githubusercontent.com/4060799/134973649-3d072adc-610a-4d4d-bb4c-d23ad1546c2a.png)

#### Version

node206.mempool.space (v2.3.0-dev) [d0a85091] 

### Steps to reproduce

Stare at the chart and move the pointer.

### Expected behaviour

The chart is clearly visible without occlusion especially at the timestamp currently being investigated.

### Actual behaviour

The disks in combination with the low contrast between some of the band colors and the background make it hard to tell whether one is actually hovering exactly over the peak, how sharp the drop was, and generally disrupt the chart.

**Comment by MiguelMedeiros** [comment]
Hello Xekyo! Thank you so much for the feedback! :heart: 

I'm already working on a way to remove the circular buttons that appears on mouseover.

This behavior happens because there are times when some lines have zero values (no rates in that range), so the circles are on top of each other, causing this bug.

My idea is to remove these circles and try to catch the event/action that are triggered when we hover over the colored area.
I don't know if this would be possible with this new lib, I'm still investigating these "events" to see if I can adapt for this usability.

**Comment by Xekyo** [comment]
@MiguelMedeiros: Ah thanks, I didn't realize you were working on this already. @wiz had just asked me to take another look, and since the UX overhaul had landed, I thought I'd file it separately.
