### ISSUE TITLE
Add RBF true/false when you call `/api/tx/:txid`

### ISSUE THREAD

**Issue by 0xAsteria** [mempool/mempool#896]
self explanatory!

**Comment by softsimon** [comment]
We are not going to add this because the information for RBF is already there.

Basically follow the rules here: https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki#summary

This is how we detect it: https://github.com/mempool/mempool/blob/master/backend/src/api/common.ts#L42

Also the `/api/tx` API is part of the separate `blockstream/electrs` project
