### ISSUE TITLE
Don’t display difficulty adjustment if recently adjusted

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#927]
Immediately after a difficulty adjustment there isn't enough data to make a useful estimate. We should hide the estimate with "TBD" if insufficient data, say 200 blocks.

**Comment by manasgandy** [comment]
I'm interested in taking this up but need help in understanding the code structure

**Comment by softsimon** [comment]
@manasgandy  How this issue should be solved:

The first 144 blocks (24 hours) after an adjustment. The GUI should display TBA and the backend API för Difficulty should return 0 as estimated adjustment during this same time.

The TBA can be solved by adding a condition in `dashboard.component.html` to show TBA instead of the current estimate, and TBA should also be a new i18n translatable string.

The backend api for the difficulty is in `routes.ts` in the getDifficultyChange method.

**Comment by MiguelMedeiros** [comment]
@wiz @softsimon I don't think this should be the best way to solve this usability issue.

I say usability, because the calculations are correct, but the impression is that the data is incorrect due to the great volatility at the beginning.

My suggestion would be to keep the **difficulty change** value and add a **precision number**. 

---
Example:

10 blocks have passed since the start of the new difficulty setting, obviously the value will change quickly. 
We can add: **precision 10/2016 * 100 = 0.49%**

With the amount of mined blocks increasing, the precision would increase, let's say there are 10 blocks to finish the difficulty change, the precision would be: **2006/2016 * 100 = 99.5%**

What do you think about this possible solution?
